name: üöÄ Deploy Notebooks to Databricks PROD (from main)

on:
  push:
    branches:
      - release
      - prod

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest

    steps:
      - name: üì• Checkout repository
        uses: actions/checkout@v3

      - name: ‚öôÔ∏è Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: üì¶ Install Databricks CLI
        run: pip install databricks-cli

      # V√©rification des secrets PROD
      - name: üß© Check secrets presence
        env:
          DATABRICKS_HOST: https://adb-690688979154426.6.azuredatabricks.net/
          DATABRICKS_TOKEN: dapi66fd064472135d2030cf4e094435f203
        run: |
          if [ -z "$DATABRICKS_HOST" ]; then
            echo "‚ùå ERREUR: DATABRICKS_HOST_PROD est vide !"
            exit 1
          fi
          if [ -z "$DATABRICKS_TOKEN" ]; then
            echo "‚ùå ERREUR: DATABRICKS_TOKEN_PROD est vide !"
            exit 1
          fi
          echo "‚úÖ Secrets PROD correctement inject√©s."

      # D√©ploiement vers PROD
      - name: üöÄ Deploy notebooks to Databricks PROD
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_PROD }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_PROD }}
        run: |
          echo "Connexion √† Databricks PROD..."
          databricks workspace ls /
          echo "‚úÖ Connexion OK"

          echo "D√©ploiement des notebooks vers /Shared/sncfdatalab_prod ..."
          databricks workspace import_dir notebooks /Shared/sncfdatalab_prod --overwrite
          echo "‚úÖ D√©ploiement termin√© avec succ√®s !"
